### ISSUE TITLE
assemble_coeffs function in ./examples/spectrograms.py returns error

### ISSUE THREAD

**Issue by kungfujam** [grrrr/nsgt#15]
Observing `c` created on [line 108](https://github.com/kungfujam/nsgt/blob/master/examples/spectrogram.py#L108), I see it generates objects of dimension 1 x 66 (a 2d array) therefore the function complains that the index [2] is out of range. This error may well be due to my misunderstanding of arguments.

```
$ ./spectrogram.py /path/to/wav/audio.wav'
Traceback (most recent call last):
  File "./spectrogram.py", line 112, in <module>
    coefs = assemble_coeffs(c, ncoefs)
  File "./spectrogram.py", line 27, in assemble_coeffs
    out = np.empty((ncoefs,cq0.shape[1],cq0.shape[2]), dtype=cq0.dtype)
```

**Comment by kungfujam** [comment]
I've had a crack at diagnosing - struggled with the generators. Running `np.array(list(c)).shape` returns `(3, 2, 66)` i.e. c is a generator that produces lists of lists ('shape' (2,66)). Is this as expected or is something going wrong upstream? I'm afraid I've run out of time trying to pick through `NSGT_sliced.forward`.

**Comment by grrrr** [comment]
The list of lists is on purpose, because the output is not necessarily rectangular (only with —matrixform it is).

I would suggest that you start with a set of trusty command line options, like

myinput.wav
—output=myoutput.h5
--fmin=80
--fmax=14000
--bins=202
--scale=log
--real
--matrixform
--reducedform=2
--fps=100
--downmix-after

and --plot, if you like

**Comment by kungfujam** [comment]
Ok, thanks for the tip. I can get it to run with just the argument `--matrixform` added. The documented help for this is simply "Use regular time division over frequency bins (matrix form)"; have you any clues as to why running without this doesn't work. Is there a bug here or is this simply expected?
